package app.rickandmorty.designsystem.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

private val LightPrimary = Color(0xFF426900)
private val LightOnPrimary = Color(0xFFFFFFFF)
private val LightPrimaryContainer = Color(0xFFBAF46D)
private val LightOnPrimaryContainer = Color(0xFF112000)
private val LightSecondary = Color(0xFF586249)
private val LightOnSecondary = Color(0xFFFFFFFF)
private val LightSecondaryContainer = Color(0xFFDCE7C7)
private val LightOnSecondaryContainer = Color(0xFF161E0B)
private val LightTertiary = Color(0xFF386662)
private val LightOnTertiary = Color(0xFFFFFFFF)
private val LightTertiaryContainer = Color(0xFFBCECE7)
private val LightOnTertiaryContainer = Color(0xFF00201E)
private val LightError = Color(0xFFBA1A1A)
private val LightErrorContainer = Color(0xFFFFDAD6)
private val LightOnError = Color(0xFFFFFFFF)
private val LightOnErrorContainer = Color(0xFF410002)
private val LightBackground = Color(0xFFFDFCF5)
private val LightOnBackground = Color(0xFF1B1C18)
private val LightOutline = Color(0xFF75796C)
private val LightInverseOnSurface = Color(0xFFF2F1E9)
private val LightInverseSurface = Color(0xFF30312C)
private val LightInversePrimary = Color(0xFF9FD754)
private val LightSurfaceTint = Color(0xFF426900)
private val LightOutlineVariant = Color(0xFFC5C8B9)
private val LightScrim = Color(0xFF000000)
private val LightSurface = Color(0xFFFBFAF2)
private val LightOnSurface = Color(0xFF1B1C18)
private val LightSurfaceVariant = Color(0xFFE1E4D5)
private val LightOnSurfaceVariant = Color(0xFF44483D)

private val DarkPrimary = Color(0xFF9FD754)
private val DarkOnPrimary = Color(0xFF203600)
private val DarkPrimaryContainer = Color(0xFF314F00)
private val DarkOnPrimaryContainer = Color(0xFFBAF46D)
private val DarkSecondary = Color(0xFFC0CBAC)
private val DarkOnSecondary = Color(0xFF2A331E)
private val DarkSecondaryContainer = Color(0xFF414A33)
private val DarkOnSecondaryContainer = Color(0xFFDCE7C7)
private val DarkTertiary = Color(0xFFA0D0CB)
private val DarkOnTertiary = Color(0xFF003734)
private val DarkTertiaryContainer = Color(0xFF1F4E4B)
private val DarkOnTertiaryContainer = Color(0xFFBCECE7)
private val DarkError = Color(0xFFFFB4AB)
private val DarkErrorContainer = Color(0xFF93000A)
private val DarkOnError = Color(0xFF690005)
private val DarkOnErrorContainer = Color(0xFFFFDAD6)
private val DarkBackground = Color(0xFF1B1C18)
private val DarkOnBackground = Color(0xFFE3E3DB)
private val DarkOutline = Color(0xFF8F9285)
private val DarkInverseOnSurface = Color(0xFF1B1C18)
private val DarkInverseSurface = Color(0xFFE3E3DB)
private val DarkInversePrimary = Color(0xFF426900)
private val DarkSurfaceTint = Color(0xFF9FD754)
private val DarkOutlineVariant = Color(0xFF44483D)
private val DarkScrim = Color(0xFF000000)
private val DarkSurface = Color(0xFF121410)
private val DarkOnSurface = Color(0xFFC7C7C0)
private val DarkSurfaceVariant = Color(0xFF44483D)
private val DarkOnSurfaceVariant = Color(0xFFC5C8B9)

internal val RamLightColorScheme = lightColorScheme(
    primary = LightPrimary,
    onPrimary = LightOnPrimary,
    primaryContainer = LightPrimaryContainer,
    onPrimaryContainer = LightOnPrimaryContainer,
    secondary = LightSecondary,
    onSecondary = LightOnSecondary,
    secondaryContainer = LightSecondaryContainer,
    onSecondaryContainer = LightOnSecondaryContainer,
    tertiary = LightTertiary,
    onTertiary = LightOnTertiary,
    tertiaryContainer = LightTertiaryContainer,
    onTertiaryContainer = LightOnTertiaryContainer,
    error = LightError,
    errorContainer = LightErrorContainer,
    onError = LightOnError,
    onErrorContainer = LightOnErrorContainer,
    background = LightBackground,
    onBackground = LightOnBackground,
    outline = LightOutline,
    inverseOnSurface = LightInverseOnSurface,
    inverseSurface = LightInverseSurface,
    inversePrimary = LightInversePrimary,
    surfaceTint = LightSurfaceTint,
    outlineVariant = LightOutlineVariant,
    scrim = LightScrim,
    surface = LightSurface,
    onSurface = LightOnSurface,
    surfaceVariant = LightSurfaceVariant,
    onSurfaceVariant = LightOnSurfaceVariant,
)

internal val RamDarkColorScheme = darkColorScheme(
    primary = DarkPrimary,
    onPrimary = DarkOnPrimary,
    primaryContainer = DarkPrimaryContainer,
    onPrimaryContainer = DarkOnPrimaryContainer,
    secondary = DarkSecondary,
    onSecondary = DarkOnSecondary,
    secondaryContainer = DarkSecondaryContainer,
    onSecondaryContainer = DarkOnSecondaryContainer,
    tertiary = DarkTertiary,
    onTertiary = DarkOnTertiary,
    tertiaryContainer = DarkTertiaryContainer,
    onTertiaryContainer = DarkOnTertiaryContainer,
    error = DarkError,
    errorContainer = DarkErrorContainer,
    onError = DarkOnError,
    onErrorContainer = DarkOnErrorContainer,
    background = DarkBackground,
    onBackground = DarkOnBackground,
    outline = DarkOutline,
    inverseOnSurface = DarkInverseOnSurface,
    inverseSurface = DarkInverseSurface,
    inversePrimary = DarkInversePrimary,
    surfaceTint = DarkSurfaceTint,
    outlineVariant = DarkOutlineVariant,
    scrim = DarkScrim,
    surface = DarkSurface,
    onSurface = DarkOnSurface,
    surfaceVariant = DarkSurfaceVariant,
    onSurfaceVariant = DarkOnSurfaceVariant,
)
