modules:
  - app
  - core/app-info
  - core/base
  - core/coil
  - core/coil-logger
  - core/compose-diagnostic
  - core/coroutines
  - core/crashlytics
  - core/datastore
  - core/design-system
  - core/filesystem
  - core/json
  - core/ktor
  - core/l10n
  - core/logger-crashlytics
  - core/logger-debug
  - core/metro-common
  - core/navigation
  - core/navigation-serialization-processor
  - core/navigation-serialization-runtime
  - core/paging
  - core/process-lifecycle
  - core/resource-state
  - core/root-content
  - core/startup
  - core/strict-mode
  - core/ui
  - core/ui-tooling-preview
  - data/data-character-api
  - data/data-character-impl
  - data/data-database-api
  - data/data-database-impl
  - data/data-debug-api
  - data/data-debug-impl
  - data/data-episode-api
  - data/data-episode-impl
  - data/data-license-api
  - data/data-license-impl
  - data/data-locale-api
  - data/data-locale-impl
  - data/data-location-api
  - data/data-location-impl
  - data/data-network
  - data/data-theme-api
  - data/data-theme-impl
  - plugins/badging
  - plugins/licenses
  - ui/ui-character-api
  - ui/ui-character-impl
  - ui/ui-debug-drawer
  - ui/ui-episode-api
  - ui/ui-episode-impl
  - ui/ui-location-api
  - ui/ui-location-impl
  - ui/ui-settings-api
  - ui/ui-settings-impl

plugins:
  - ./plugins/badging
  - ./plugins/licenses
