[versions]
accompanist = "0.33.2-alpha"
affectedmoduledetector = "0.2.1"
android-desugarjdklibs = "2.0.4"
android-plugin = "8.3.0-alpha12"
android-sdk-compile = "34"
android-sdk-min = "24"
android-sdk-target = "34"
androidx-activity = "1.8.0"
androidx-appcompat = "1.7.0-alpha03"
androidx-benchmark = "1.2.0"
androidx-browser = "1.6.0"
androidx-compose-bom = "2023.11.00-alpha02"
androidx-compose-compiler = "1.5.4-dev-k1.9.20-50f08dfa4b4"
androidx-compose-material3-adaptive = "1.0.0-SNAPSHOT"
androidx-compose-runtimetracing = "1.0.0-alpha04"
androidx-core = "1.12.0"
androidx-core-splashscreen = "1.0.1"
androidx-datastore = "1.1.0-alpha04"
androidx-hilt-navigation-compose = "1.1.0"
androidx-lifecycle = "2.6.2"
androidx-metrics = "1.0.0-alpha04"
androidx-navigation = "2.7.5"
androidx-profileinstaller = "1.3.1"
androidx-test-core = "1.6.0-alpha02"
androidx-test-espresso = "3.6.0-alpha01"
androidx-test-junit = "1.2.0-alpha01"
androidx-test-rules = "1.6.0-alpha01"
androidx-test-runner = "1.6.0-alpha04"
androidx-test-truth = "1.6.0-alpha01"
androidx-test-uiautomator = "2.3.0-alpha04"
androidx-tracing = "1.2.0-rc01"
androidx-window = "1.2.0-rc01"
apollo = "4.0.0-beta.2"
autodagger = "0.10.0"
cachefix = "2.8.1"
coil = "2.5.0"
debugdrawer = "0.9.8"
dependencyanalysis = "1.24.0"
easylauncher = "6.2.0"
firebase-bom = "32.5.0"
firebase-crashlytics-plugin = "2.9.9"
firebase-perf-plugin = "1.4.2"
googleservices = "4.4.0"
gradledoctor = "0.8.1"
hilt = "2.48.1"
jdk = "17"
junit4 = "4.13.2"
kotlin = "1.9.20"
kotlinx-collectionsimmutable = "0.3.6"
kotlinx-coroutines = "1.7.3"
kotlinx-datetime = "0.4.1"
ksp = "1.9.20-1.0.14"
ktlint = "0.50.0"
leakcanary = "2.12"
modulegraphassert = "2.5.0"
okhttp = "4.12.0"
play-osslicenses = "17.0.1"
play-osslicenses-plugin = "0.10.6"
slack-composelints = "1.2.0"
sortdependencies = "0.4"
spotless = "6.22.0"
testparameterinjector = "1.14"
timber = "5.0.1"
truth = "1.1.5"
turbine = "1.0.0"
wire = "4.9.1"

[libraries]
accompanist-placeholder-material3 = { group = "com.google.accompanist", name = "accompanist-placeholder-material3", version.ref = "accompanist" }
accompanist-testharness = { group = "com.google.accompanist", name = "accompanist-testharness", version.ref = "accompanist" }

affectedmoduledetector-plugin = { group = "com.dropbox.affectedmoduledetector", name = "affectedmoduledetector", version.ref = "affectedmoduledetector" }

android-desugarjdklibs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "android-desugarjdklibs" }
android-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "android-plugin" }

androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-benchmark-macro = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "androidx-benchmark" }
androidx-browser = { group = "androidx.browser", name = "browser", version.ref = "androidx-browser" }
androidx-compose-animation = { group = "androidx.compose.animation", name = "animation" }
androidx-compose-bom = { group = "dev.chrisbanes.compose", name = "compose-bom", version.ref = "androidx-compose-bom" }
androidx-compose-compiler = { group = "androidx.compose.compiler", name = "compiler", version.ref = "androidx-compose-compiler" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout" }
androidx-compose-material-iconsextended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material3-adaptive = { group = "androidx.compose.material3", name = "material3-adaptive", version.ref = "androidx-compose-material3-adaptive" }
androidx-compose-material3-adaptive-navigationsuite = { group = "androidx.compose.material3", name = "material3-adaptive-navigation-suite", version.ref = "androidx-compose-material3-adaptive" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
androidx-compose-runtime-tracing = { group = "androidx.compose.runtime", name = "runtime-tracing", version.ref = "androidx-compose-runtimetracing" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-test = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-text-googlefonts = { group = "androidx.compose.ui", name = "ui-text-google-fonts" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-util = { group = "androidx.compose.ui", name = "ui-util" }
androidx-core = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidx-core-splashscreen" }
androidx-datastore = { group = "androidx.datastore", name = "datastore", version.ref = "androidx-datastore" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidx-hilt-navigation-compose" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-testing = { group = "androidx.lifecycle", name = "lifecycle-runtime-testing", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-metrics = { group = "androidx.metrics", name = "metrics-performance", version.ref = "androidx-metrics" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidx-navigation" }
androidx-navigation-testing = { group = "androidx.navigation", name = "navigation-testing", version.ref = "androidx-navigation" }
androidx-profileinstaller = { group = "androidx.profileinstaller", name = "profileinstaller", version.ref = "androidx-profileinstaller" }
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "androidx-test-core" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-test-espresso" }
androidx-test-junit = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "androidx-test-junit" }
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "androidx-test-rules" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidx-test-runner" }
androidx-test-truth = { group = "androidx.test.ext", name = "truth", version.ref = "androidx-test-truth" }
androidx-test-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "androidx-test-uiautomator" }
androidx-tracing = { group = "androidx.tracing", name = "tracing-ktx", version.ref = "androidx-tracing" }
androidx-window = { group = "androidx.window", name = "window", version.ref = "androidx-window" }

apollo-adapters = { group = "com.apollographql.apollo3", name = "apollo-adapters", version.ref = "apollo" }
apollo-api = { group = "com.apollographql.apollo3", name = "apollo-api", version.ref = "apollo" }
apollo-normalizedcache = { group = "com.apollographql.apollo3", name = "apollo-normalized-cache", version.ref = "apollo" }
apollo-normalizedcache-sqlite = { group = "com.apollographql.apollo3", name = "apollo-normalized-cache-sqlite", version.ref = "apollo" }
apollo-runtime = { group = "com.apollographql.apollo3", name = "apollo-runtime", version.ref = "apollo" }

autodagger-compiler = { group = "se.ansman.dagger.auto", name = "compiler", version.ref = "autodagger" }
autodagger-core = { group = "se.ansman.dagger.auto", name = "core", version.ref = "autodagger" }

coil = { group = "io.coil-kt", name = "coil", version.ref = "coil" }
coil-base = { group = "io.coil-kt", name = "coil-base", version.ref = "coil" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }

debugdrawer = { group = "au.com.gridstone.debugdrawer", name = "debugdrawer", version.ref = "debugdrawer" }
debugdrawer-okhttplogger = { group = "au.com.gridstone.debugdrawer", name = "debugdrawer-okhttp-logger", version.ref = "debugdrawer" }
debugdrawer-timber = { group = "au.com.gridstone.debugdrawer", name = "debugdrawer-timber", version.ref = "debugdrawer" }

dependencyanalysis-plugin = { group = "com.autonomousapps", name = "dependency-analysis-gradle-plugin", version.ref = "dependencyanalysis" }

firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics-ktx" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics-ktx" }
firebase-perf = { group = "com.google.firebase", name = "firebase-perf-ktx" }

hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-android-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt" }
hilt-core = { group = "com.google.dagger", name = "hilt-core", version.ref = "hilt" }

junit4 = { group = "junit", name = "junit", version.ref = "junit4" }

kotlin-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

kotlinx-collectionsimmutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinx-collectionsimmutable" }

kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }

kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }

leakcanary = { group = "com.squareup.leakcanary", name = "leakcanary-android-startup", version.ref = "leakcanary" }
leakcanary-plumber = { group = "com.squareup.leakcanary", name = "plumber-android-startup", version.ref = "leakcanary" }

okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-logginginterceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }

play-osslicenses = { group = "com.google.android.gms", name = "play-services-oss-licenses", version.ref = "play-osslicenses" }

slack-compose-lints = { group = "com.slack.lint.compose", name = "compose-lint-checks", version.ref = "slack-composelints" }

spotless-plugin = { group = "com.diffplug.spotless", name = "spotless-plugin-gradle", version.ref = "spotless" }

testparameterinjector = { group = "com.google.testparameterinjector", name = "test-parameter-injector", version.ref = "testparameterinjector" }

timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }

truth = { group = "com.google.truth", name = "truth", version.ref = "truth" }

turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }

wire-plugin = { group = "com.squareup.wire", name = "wire-gradle-plugin", version.ref = "wire" }
wire-runtime = { group = "com.squareup.wire", name = "wire-runtime", version.ref = "wire" }

[plugins]
# Convention plugins
rickandmorty-android-application = { id = "app.rickandmorty.android-application", version = "unspecified" }
rickandmorty-android-library = { id = "app.rickandmorty.android-library", version = "unspecified" }
rickandmorty-android-test = { id = "app.rickandmorty.android-test", version = "unspecified" }
rickandmorty-autodagger = { id = "app.rickandmorty.autodagger", version = "unspecified" }
rickandmorty-compose = { id = "app.rickandmorty.compose", version = "unspecified" }
rickandmorty-firebase-crashlytics = { id = "app.rickandmorty.firebase-crashlytics", version = "unspecified" }
rickandmorty-firebase-perf = { id = "app.rickandmorty.firebase-perf", version = "unspecified" }
rickandmorty-hilt = { id = "app.rickandmorty.hilt", version = "unspecified" }
rickandmorty-jvm-library = { id = "app.rickandmorty.jvm-library", version = "unspecified" }
rickandmorty-osslicenses = { id = "app.rickandmorty.oss-licenses", version = "unspecified" }
rickandmorty-root = { id = "app.rickandmorty.root", version = "unspecified" }
rickandmorty-wire = { id = "app.rickandmorty.wire", version = "unspecified" }

affectedmoduledetector = { id = "com.dropbox.affectedmoduledetector", version.ref = "affectedmoduledetector" }
android-application = { id = "com.android.application", version.ref = "android-plugin" }
android-library = { id = "com.android.library", version.ref = "android-plugin" }
android-test = { id = "com.android.test", version.ref = "android-plugin" }
apollo = { id = "com.apollographql.apollo3", version.ref = "apollo" }
baselineprofile = { id = "androidx.baselineprofile", version.ref = "androidx-benchmark" }
cachefix = { id = "org.gradle.android.cache-fix", version.ref = "cachefix" }
dependencyanalysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "dependencyanalysis" }
easylauncher = { id = "com.starter.easylauncher", version.ref = "easylauncher" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics-plugin" }
firebase-perf = { id = "com.google.firebase.firebase-perf", version.ref = "firebase-perf-plugin" }
googleservices = { id = "com.google.gms.google-services", version.ref = "googleservices" }
gradledoctor = { id = "com.osacky.doctor", version.ref = "gradledoctor" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
modulegraphassert = { id = "com.jraska.module.graph.assertion", version.ref = "modulegraphassert" }
play-osslicenses = { id = "com.google.android.gms.oss-licenses-plugin", version.ref = "play-osslicenses-plugin" }
sortdependencies = { id = "com.squareup.sort-dependencies", version.ref = "sortdependencies" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
wire = { id = "com.squareup.wire", version.ref = "wire" }
