[versions]
affectedmoduledetector = "0.3.1"
android-desugarjdklibs = "2.0.4"
android-plugin = "8.4.0"
android-sdk-compile = "34"
android-sdk-min = "24"
android-sdk-target = "34"
android-tools = "31.4.0"
androidx-activity = "1.9.0"
androidx-appcompat = "1.7.0-alpha03"
androidx-benchmark = "1.2.4"
androidx-compose-bom = "2024.04.00-alpha02"
androidx-compose-compiler = "1.5.12"
androidx-compose-runtimetracing = "1.0.0-beta01"
androidx-core = "1.13.0"
androidx-core-splashscreen = "1.2.0-alpha01"
androidx-datastore = "1.1.0"
androidx-hilt-navigation-compose = "1.2.0"
androidx-lifecycle = "2.8.0-rc01"
androidx-metrics = "1.0.0-beta01"
androidx-navigation = "2.8.0-alpha07"
androidx-paging = "3.3.0-beta01"
androidx-profileinstaller = "1.4.0-alpha01"
androidx-room = "2.6.1"
androidx-test-core = "1.6.0-alpha06"
androidx-test-espresso = "3.6.0-alpha04"
androidx-test-junit = "1.2.0-alpha04"
androidx-test-rules = "1.6.0-alpha04"
androidx-test-runner = "1.6.0-alpha07"
androidx-test-truth = "1.6.0-alpha04"
androidx-test-uiautomator = "2.3.0"
androidx-tracing = "1.2.0"
androidx-window = "1.3.0-beta01"
apollo = "4.0.0-beta.6"
autodagger = "1.1.0"
cachefix = "3.0.1"
coil = "3.0.0-alpha06"
dependencyanalysis = "1.31.0"
easylauncher = "6.3.0"
firebase-bom = "32.8.1"
firebase-crashlytics-plugin = "2.9.9"
firebase-perf-plugin = "1.4.2"
googleservices = "4.4.1"
gradledoctor = "0.9.2"
haze = "0.7.0"
hilt = "2.51.1"
java-jdk = "21"
java-target = "17"
junit4 = "4.13.2"
kotlin = "1.9.23"
kotlinx-atomicfu = "0.24.0"
kotlinx-collectionsimmutable = "0.3.7"
kotlinx-coroutines = "1.8.0"
kotlinx-datetime = "0.5.0"
ksp = "1.9.23-1.0.20"
ktlint = "1.1.1"
leakcanary = "2.14"
modulegraphassert = "2.5.0"
okhttp = "5.0.0-alpha.14"
play-osslicenses = "17.0.1"
play-osslicenses-plugin = "0.10.6"
slack-composelints = "1.3.1"
sortdependencies = "0.6"
spotless = "6.25.0"
store = "5.0.0"
testparameterinjector = "1.16"
timber = "5.0.1"
truth = "1.4.2"
turbine = "1.1.0"
wire = "4.9.9"

[libraries]
affectedmoduledetector-plugin = { group = "com.dropbox.affectedmoduledetector", name = "affectedmoduledetector", version.ref = "affectedmoduledetector" }

android-desugarjdklibs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "android-desugarjdklibs" }
android-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "android-plugin" }
android-tools-common = { group = "com.android.tools", name = "common", version.ref = "android-tools" }

androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-benchmark-macro = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "androidx-benchmark" }
androidx-compose-animation = { group = "androidx.compose.animation", name = "animation" }
androidx-compose-bom = { group = "dev.chrisbanes.compose", name = "compose-bom", version.ref = "androidx-compose-bom" }
androidx-compose-compiler = { group = "androidx.compose.compiler", name = "compiler", version.ref = "androidx-compose-compiler" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout" }
androidx-compose-material-iconsextended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material3-adaptive = { group = "androidx.compose.material3.adaptive", name = "adaptive" }
androidx-compose-material3-adaptive-navigationsuite = { group = "androidx.compose.material3", name = "material3-adaptive-navigation-suite" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
androidx-compose-runtime-tracing = { group = "androidx.compose.runtime", name = "runtime-tracing", version.ref = "androidx-compose-runtimetracing" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-test = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-text-googlefonts = { group = "androidx.compose.ui", name = "ui-text-google-fonts" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-util = { group = "androidx.compose.ui", name = "ui-util" }
androidx-core = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidx-core-splashscreen" }
androidx-datastore = { group = "androidx.datastore", name = "datastore", version.ref = "androidx-datastore" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidx-hilt-navigation-compose" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-testing = { group = "androidx.lifecycle", name = "lifecycle-runtime-testing", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-metrics = { group = "androidx.metrics", name = "metrics-performance", version.ref = "androidx-metrics" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidx-navigation" }
androidx-navigation-testing = { group = "androidx.navigation", name = "navigation-testing", version.ref = "androidx-navigation" }
androidx-paging-common = { group = "androidx.paging", name = "paging-common", version.ref = "androidx-paging" }
androidx-paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "androidx-paging" }
androidx-paging-runtime = { group = "androidx.paging", name = "paging-runtime", version.ref = "androidx-paging" }
androidx-profileinstaller = { group = "androidx.profileinstaller", name = "profileinstaller", version.ref = "androidx-profileinstaller" }
androidx-room = { group = "androidx.room", name = "room-ktx", version.ref = "androidx-room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidx-room" }
androidx-room-paging = { group = "androidx.room", name = "room-paging", version.ref = "androidx-room" }
androidx-room-plugin = { group = "androidx.room", name = "room-gradle-plugin", version.ref = "androidx-room" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "androidx-room" }
androidx-room-testing = { group = "androidx.room", name = "room-testing", version.ref = "androidx-room" }
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "androidx-test-core" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-test-espresso" }
androidx-test-junit = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "androidx-test-junit" }
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "androidx-test-rules" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidx-test-runner" }
androidx-test-truth = { group = "androidx.test.ext", name = "truth", version.ref = "androidx-test-truth" }
androidx-test-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "androidx-test-uiautomator" }
androidx-tracing = { group = "androidx.tracing", name = "tracing-ktx", version.ref = "androidx-tracing" }
androidx-window = { group = "androidx.window", name = "window", version.ref = "androidx-window" }

apollo-adapters = { group = "com.apollographql.apollo3", name = "apollo-adapters", version.ref = "apollo" }
apollo-api = { group = "com.apollographql.apollo3", name = "apollo-api", version.ref = "apollo" }
apollo-runtime = { group = "com.apollographql.apollo3", name = "apollo-runtime", version.ref = "apollo" }

autodagger-compiler = { group = "se.ansman.dagger.auto", name = "compiler", version.ref = "autodagger" }
autodagger-core = { group = "se.ansman.dagger.auto", name = "core", version.ref = "autodagger" }
autodagger-room = { group = "se.ansman.dagger.auto", name = "androidx-room", version.ref = "autodagger" }

coil = { group = "io.coil-kt.coil3", name = "coil", version.ref = "coil" }
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-core = { group = "io.coil-kt.coil3", name = "coil-core", version.ref = "coil" }
coil-network-okhttp = { group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref = "coil" }

dependencyanalysis-plugin = { group = "com.autonomousapps", name = "dependency-analysis-gradle-plugin", version.ref = "dependencyanalysis" }

firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }
firebase-perf = { group = "com.google.firebase", name = "firebase-perf" }

gradledoctor-plugin = { group = "com.osacky.doctor", name = "doctor-plugin", version.ref = "gradledoctor" }

haze = { group = "dev.chrisbanes.haze", name = "haze", version.ref = "haze" }
haze-materials = { group = "dev.chrisbanes.haze", name = "haze-materials", version.ref = "haze" }

hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-android-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt" }
hilt-core = { group = "com.google.dagger", name = "hilt-core", version.ref = "hilt" }

junit4 = { group = "junit", name = "junit", version.ref = "junit4" }

kotlin-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

kotlinx-atomicfu = { group = "org.jetbrains.kotlinx", name = "atomicfu", version.ref = "kotlinx-atomicfu" }

kotlinx-collectionsimmutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinx-collectionsimmutable" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }

ksp-plugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }

leakcanary = { group = "com.squareup.leakcanary", name = "leakcanary-android-startup", version.ref = "leakcanary" }
leakcanary-plumber = { group = "com.squareup.leakcanary", name = "plumber-android-startup", version.ref = "leakcanary" }

okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-logginginterceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }

play-osslicenses = { group = "com.google.android.gms", name = "play-services-oss-licenses", version.ref = "play-osslicenses" }

slack-compose-lints = { group = "com.slack.lint.compose", name = "compose-lint-checks", version.ref = "slack-composelints" }

spotless-plugin = { group = "com.diffplug.spotless", name = "spotless-plugin-gradle", version.ref = "spotless" }

store = { group = "org.mobilenativefoundation.store", name = "store5", version.ref = "store" }

testparameterinjector = { group = "com.google.testparameterinjector", name = "test-parameter-injector", version.ref = "testparameterinjector" }

timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }

truth = { group = "com.google.truth", name = "truth", version.ref = "truth" }

turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }

wire-plugin = { group = "com.squareup.wire", name = "wire-gradle-plugin", version.ref = "wire" }
wire-runtime = { group = "com.squareup.wire", name = "wire-runtime", version.ref = "wire" }

[plugins]
# Convention plugins
rickandmorty-android-application = { id = "app.rickandmorty.android-application", version = "unspecified" }
rickandmorty-android-library = { id = "app.rickandmorty.android-library", version = "unspecified" }
rickandmorty-android-test = { id = "app.rickandmorty.android-test", version = "unspecified" }
rickandmorty-autodagger = { id = "app.rickandmorty.autodagger", version = "unspecified" }
rickandmorty-compose = { id = "app.rickandmorty.compose", version = "unspecified" }
rickandmorty-firebase-crashlytics = { id = "app.rickandmorty.firebase-crashlytics", version = "unspecified" }
rickandmorty-firebase-perf = { id = "app.rickandmorty.firebase-perf", version = "unspecified" }
rickandmorty-hilt = { id = "app.rickandmorty.hilt", version = "unspecified" }
rickandmorty-jvm-library = { id = "app.rickandmorty.jvm-library", version = "unspecified" }
rickandmorty-kotlin-android = { id = "app.rickandmorty.kotlin-android", version = "unspecified" }
rickandmorty-kotlin-jvm = { id = "app.rickandmorty.kotlin-jvm", version = "unspecified" }
rickandmorty-osslicenses = { id = "app.rickandmorty.oss-licenses", version = "unspecified" }
rickandmorty-room = { id = "app.rickandmorty.room", version = "unspecified" }
rickandmorty-root = { id = "app.rickandmorty.root", version = "unspecified" }
rickandmorty-wire = { id = "app.rickandmorty.wire", version = "unspecified" }

affectedmoduledetector = { id = "com.dropbox.affectedmoduledetector", version.ref = "affectedmoduledetector" }
android-application = { id = "com.android.application", version.ref = "android-plugin" }
android-library = { id = "com.android.library", version.ref = "android-plugin" }
android-test = { id = "com.android.test", version.ref = "android-plugin" }
androidx-baselineprofile = { id = "androidx.baselineprofile", version.ref = "androidx-benchmark" }
androidx-room = { id = "androidx.room", version.ref = "androidx-room" }
apollo = { id = "com.apollographql.apollo3", version.ref = "apollo" }
cachefix = { id = "org.gradle.android.cache-fix", version.ref = "cachefix" }
dependencyanalysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "dependencyanalysis" }
easylauncher = { id = "com.starter.easylauncher", version.ref = "easylauncher" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics-plugin" }
firebase-perf = { id = "com.google.firebase.firebase-perf", version.ref = "firebase-perf-plugin" }
googleservices = { id = "com.google.gms.google-services", version.ref = "googleservices" }
gradledoctor = { id = "com.osacky.doctor", version.ref = "gradledoctor" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
modulegraphassert = { id = "com.jraska.module.graph.assertion", version.ref = "modulegraphassert" }
play-osslicenses = { id = "com.google.android.gms.oss-licenses-plugin", version.ref = "play-osslicenses-plugin" }
sortdependencies = { id = "com.squareup.sort-dependencies", version.ref = "sortdependencies" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
wire = { id = "com.squareup.wire", version.ref = "wire" }
