[versions]
accompanist = "0.31.2-alpha"
androidCompileSdk = "34"
androidDesugarJdkLibs = "2.0.3"
androidGradlePlugin = "8.2.0-alpha07"
androidMinSdk = "24"
androidTargetSdk = "34"
androidxActivity = "1.8.0-alpha05"
androidxAppcompat = "1.7.0-alpha02"
androidxBenchmark = "1.2.0-alpha14"
androidxBrowser = "1.5.0"
androidxComposeBom = "2023.04.00-beta02"
androidxComposeCompiler = "1.4.7"
androidxComposeRuntimeTracing = "1.0.0-alpha03"
androidxCore = "1.12.0-alpha05"
androidxCoreSplashscreen = "1.0.1"
androidxDatastore = "1.1.0-alpha04"
androidxHiltNavigationCompose = "1.1.0-alpha01"
androidxLifecycle = "2.6.1"
androidxMetrics = "1.0.0-alpha04"
androidxNavigation = "2.7.0-beta01"
androidxProfileinstaller = "1.3.1"
androidxStartup = "1.2.0-alpha02"
androidxTestCore = "1.6.0-alpha01"
androidxTestEspresso = "3.6.0-alpha01"
androidxTestExtJunit = "1.2.0-alpha01"
androidxTestExtTruth = "1.6.0-alpha01"
androidxTestRules = "1.6.0-alpha01"
androidxTestRunner = "1.6.0-alpha02"
androidxTracing = "1.2.0-rc01"
androidxUiAutomator = "2.3.0-alpha03"
androidxWindow = "1.2.0-alpha02"
apollo = "4.0.0-alpha.1"
cacheFix = "2.7.1"
coil = "2.4.0"
composeLints = "1.2.0"
dependencyAnalysis = "1.20.0"
easylauncher = "6.2.0"
firebaseBom = "32.1.0"
firebaseCrashlyticsGradlePlugin = "2.9.5"
firebasePerfGradlePlugin = "1.4.2"
googleServices = "4.3.15"
gradleDoctor = "0.8.1"
hilt = "2.46.1"
java = "17"
junit4 = "4.13.2"
kotlin = "1.8.21"
kotlinxCollectionsImmutable = "0.3.5"
kotlinxCoroutines = "1.7.1"
kotlinxDatetime = "0.4.0"
ksp = "1.8.21-1.0.11"
leakcanary = "2.11"
moduleGraphAssert = "2.4.0"
nodeGradle = "5.0.0"
okhttp = "4.11.0"
playOssLicenses = "17.0.1"
playOssLicensesGradlePlugin = "0.10.6"
protobuf = "3.23.2"
protobufGradlePlugin = "0.9.3"
sortDependencies = "0.2"
spotless = "6.19.0"
testParameterInjector = "1.12"
timber = "5.0.1"
truth = "1.1.4"
turbine = "0.13.0"

[libraries]
accompanist-adaptive = { group = "com.google.accompanist", name = "accompanist-adaptive", version.ref = "accompanist" }
accompanist-placeholder-material3 = { group = "com.google.accompanist", name = "accompanist-placeholder-material3", version.ref = "accompanist" }
accompanist-testharness = { group = "com.google.accompanist", name = "accompanist-testharness", version.ref = "accompanist" }

android-desugarJdkLibs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "androidDesugarJdkLibs" }

android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }

androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppcompat" }
androidx-benchmark-macro = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "androidxBenchmark" }
androidx-browser = { group = "androidx.browser", name = "browser", version.ref = "androidxBrowser" }
androidx-compose-animation = { group = "androidx.compose.animation", name = "animation" }
androidx-compose-bom = { group = "dev.chrisbanes.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-compiler = { group = "androidx.compose.compiler", name = "compiler", version.ref = "androidxComposeCompiler" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout" }
androidx-compose-material-iconsExtended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material3-windowSizeClass = { group = "androidx.compose.material3", name = "material3-window-size-class" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
androidx-compose-runtime-tracing = { group = "androidx.compose.runtime", name = "runtime-tracing", version.ref = "androidxComposeRuntimeTracing" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-test = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-text-googleFonts = { group = "androidx.compose.ui", name = "ui-text-google-fonts" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-util = { group = "androidx.compose.ui", name = "ui-util" }
androidx-core = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidxCoreSplashscreen" }
androidx-datastore = { group = "androidx.datastore", name = "datastore", version.ref = "androidxDatastore" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidxHiltNavigationCompose" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidx-lifecycle-runtime-testing = { group = "androidx.lifecycle", name = "lifecycle-runtime-testing", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
androidx-metrics = { group = "androidx.metrics", name = "metrics-performance", version.ref = "androidxMetrics" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidxNavigation" }
androidx-navigation-testing = { group = "androidx.navigation", name = "navigation-testing", version.ref = "androidxNavigation" }
androidx-profileinstaller = { group = "androidx.profileinstaller", name = "profileinstaller", version.ref = "androidxProfileinstaller" }
androidx-startup = { group = "androidx.startup", name = "startup-runtime", version.ref = "androidxStartup" }
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "androidxTestCore" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidxTestEspresso" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "androidxTestExtJunit" }
androidx-test-ext-truth = { group = "androidx.test.ext", name = "truth", version.ref = "androidxTestExtTruth" }
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "androidxTestRules" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidxTestRunner" }
androidx-test-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "androidxUiAutomator" }
androidx-tracing = { group = "androidx.tracing", name = "tracing-ktx", version.ref = "androidxTracing" }
androidx-window = { group = "androidx.window", name = "window", version.ref = "androidxWindow" }

apollo-adapters = { group = "com.apollographql.apollo3", name = "apollo-adapters", version.ref = "apollo" }
apollo-api = { group = "com.apollographql.apollo3", name = "apollo-api", version.ref = "apollo" }
apollo-normalizedCache = { group = "com.apollographql.apollo3", name = "apollo-normalized-cache", version.ref = "apollo" }
apollo-normalizedCache-sqlite = { group = "com.apollographql.apollo3", name = "apollo-normalized-cache-sqlite", version.ref = "apollo" }
apollo-runtime = { group = "com.apollographql.apollo3", name = "apollo-runtime", version.ref = "apollo" }

coil = { group = "io.coil-kt", name = "coil", version.ref = "coil" }
coil-base = { group = "io.coil-kt", name = "coil-base", version.ref = "coil" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }

compose-lints = { group = "com.slack.lint.compose", name = "compose-lint-checks", version.ref = "composeLints" }

dependencyAnalysis-gradlePlugin = { group = "com.autonomousapps", name = "dependency-analysis-gradle-plugin", version.ref = "dependencyAnalysis" }

firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics-ktx" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics-ktx" }
firebase-perf = { group = "com.google.firebase", name = "firebase-perf-ktx" }

hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-core = { group = "com.google.dagger", name = "hilt-core", version.ref = "hilt" }
hilt-android-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt" }

junit4 = { group = "junit", name = "junit", version.ref = "junit4" }

kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

kotlinx-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinxCollectionsImmutable" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinxDatetime" }

leakcanary = { group = "com.squareup.leakcanary", name = "leakcanary-android-startup", version.ref = "leakcanary" }
leakcanary-plumber = { group = "com.squareup.leakcanary", name = "plumber-android-startup", version.ref = "leakcanary" }

okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-loggingInterceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }

play-ossLicenses = { group = "com.google.android.gms", name = "play-services-oss-licenses", version.ref = "playOssLicenses" }
play-ossLicenses-gradlePlugin = { group = "com.google.android.gms", name = "oss-licenses-plugin", version.ref = "playOssLicensesGradlePlugin" }

protobuf-gradlePlugin = { group = "com.google.protobuf", name = "protobuf-gradle-plugin", version.ref = "protobufGradlePlugin" }
protobuf-kotlin-lite = { group = "com.google.protobuf", name = "protobuf-kotlin-lite", version.ref = "protobuf" }
protobuf-protoc = { group = "com.google.protobuf", name = "protoc", version.ref = "protobuf" }

spotless-gradlePlugin = { group = "com.diffplug.spotless", name = "spotless-plugin-gradle", version.ref = "spotless" }

testParameterInjector = { group = "com.google.testparameterinjector", name = "test-parameter-injector", version.ref = "testParameterInjector" }

timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }

truth = { group = "com.google.truth", name = "truth", version.ref = "truth" }

turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
android-test = { id = "com.android.test", version.ref = "androidGradlePlugin" }
apollo = { id = "com.apollographql.apollo3", version.ref = "apollo" }
baselineprofile = { id = "androidx.baselineprofile", version.ref = "androidxBenchmark" }
cacheFix = { id = "org.gradle.android.cache-fix", version.ref = "cacheFix" }
dependencyAnalysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "dependencyAnalysis" }
easylauncher = { id = "com.starter.easylauncher", version.ref = "easylauncher" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlyticsGradlePlugin" }
firebase-perf = { id = "com.google.firebase.firebase-perf", version.ref = "firebasePerfGradlePlugin" }
googleServices = { id = "com.google.gms.google-services", version.ref = "googleServices" }
gradleDoctor = { id = "com.osacky.doctor", version.ref = "gradleDoctor" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
moduleGraphAssert = { id = "com.jraska.module.graph.assertion", version.ref = "moduleGraphAssert" }
nodeGradle = { id = "com.github.node-gradle.node", version.ref = "nodeGradle" }
play-ossLicenses = { id = "com.google.android.gms.oss-licenses-plugin" }
protobuf = { id = "com.google.protobuf", version.ref = "protobufGradlePlugin" }
sortDependencies = { id = "com.squareup.sort-dependencies", version.ref = "sortDependencies" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
