name: Decrypt secrets

description: Decrypt secrets and write the release signing configuration

inputs:
  key:
    description: Decrypt key
    required: true
  keystore-password:
    description: Release keystore password
    required: true
  key-password:
    description: Release key password
    required: true

runs:
  using: 'composite'

  steps:
    - run: |
        ./scripts/decrypt-secret.sh -k ${{ inputs.key }} firebase/google-services.gpg app/google-services.json
        ./scripts/decrypt-secret.sh -k ${{ inputs.key }} keystore/release.gpg keystore/release.jks
        cat > app/keystore.properties <<EOF
        storeFile=../keystore/release.jks
        storePassword=${{ inputs.keystore-password }}
        keyAlias=release
        keyPassword=${{ inputs.key-password }}
        EOF
      shell: bash
