package app.rickandmorty.license

import app.rickandmorty.data.license.LicensesJsonSource
import dev.zacsweers.metro.AppScope
import dev.zacsweers.metro.ContributesBinding

/** Reads `resources/aboutlibraries.json`, generated by `./kotlin do updateLicenses -m app`. */
@ContributesBinding(AppScope::class)
class ResourceLicensesJsonSource : LicensesJsonSource {
  override fun getLicensesJson(): String =
    checkNotNull(javaClass.getResourceAsStream("/aboutlibraries.json")) {
        "aboutlibraries.json is missing"
      }
      .reader()
      .use { it.readText() }
}
