name: Auto update

on:
  push:

concurrency:
  group: auto-update-${{ github.ref }}
  cancel-in-progress: true

jobs:
  auto-update:
    runs-on: ubuntu-latest

    steps:
      - name: Auto update
        uses: tibdex/auto-update@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
