name: TODO <> GitHub issues

on:
  push:
    branches:
      - main

concurrency:
  group: todo-${{ github.ref }}
  cancel-in-progress: true

jobs:
  todo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Create GitHub issues
        uses: alstr/todo-to-issue-action@v4
